FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install cors
RUN npm install --save-dev @types/cors

COPY . .

RUN npm run build

EXPOSE 5555

CMD ["npm", "run", "start"]
